POST http://127.0.0.1:8080/api/v1/user/register HTTP/1.1
Content-Type: application/json

{
	"Email"    : "wltjd9870@naver.com",
	"Password" : "test",
	"Name"     : "jisung"
}
###

POST http://127.0.0.1:8080/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
	"Email"    : "wltjd9870@naver.com",
	"Password" : "test"
}

###
GET http://127.0.0.1:8080/api/v1/health HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjExNzBlZjIwLTJlNDctMTFlZC1hODY4LTIyZmIwMDZjNzczNSIsImV4cCI6MTY2MjUxMTg4OH0.CEVRwsFdq9pUl_2Oja4tBb9gmz62Kat1BdwTw0p3RcY
Authorization-Refresh: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI1MTU0MjgsInJlZnJlc2hfdXVpZCI6IjExNzBlZmFjLTJlNDctMTFlZC1hODY4LTIyZmIwMDZjNzczNSJ9.EmddNC0g16AlFpHo3nBcKQPLfcirb4K4CKavQuKvrXw

###
POST http://127.0.0.1:8080/api/v1/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjExNzBlZjIwLTJlNDctMTFlZC1hODY4LTIyZmIwMDZjNzczNSIsImV4cCI6MTY2MjUxMTg4OH0.CEVRwsFdq9pUl_2Oja4tBb9gmz62Kat1BdwTw0p3RcY
Authorization-Refresh: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI1MTU0MjgsInJlZnJlc2hfdXVpZCI6IjExNzBlZmFjLTJlNDctMTFlZC1hODY4LTIyZmIwMDZjNzczNSJ9.EmddNC0g16AlFpHo3nBcKQPLfcirb4K4CKavQuKvrXw