database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  databaseName: gin

auth:
  accessSecret: accessSecret
  refreshSecret: refreshSecret

trace:
  endpoint: http://localhost:14268/api/traces
  serviceName: gin-tempo