version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gin
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8089:8080
volumes:
  postgres_data: